### ISSUE TITLE
clean message before searching emojis

### ISSUE THREAD

**Issue by hugofragata** [hugofragata/emojify-commits#4]
as in:

- remove punctuation ()[]./, whatever...
- added -> add
- bugs -> bug

**Comment by Fozoro** [comment]
I don't quite get what you mean by added -> add, could you elaborate.

**Comment by hugofragata** [comment]
@Fozoro the code is comparing words from the commit message and the emoji.json as is, for exemple, if a commit message contains the word "cookies" it will not show the cookie emoji, but it should. therefore, before searching with a given word it should _clean_ it
