### ISSUE TITLE
commits messages already with emoji dont work

### ISSUE THREAD

**Issue by hugofragata** [hugofragata/emojify-commits#5]
encoding problems, emoji is unicode but the script is reading the commit message file as ascii

**Comment by adrianosmarinho** [comment]
Hi @hugofragata, I was wondering if you tried to change this line in append_to_file():
```python
with open(sys.argv[1], 'r') as message_file: 
```
to
```python
with open(sys.argv[1], 'r', 'utf-8') as message_file: 
```
to check if it would solve the problem?

**Comment by hugofragata** [comment]
@adrianosmarinho 
```python
with open(sys.argv[1], 'r', encoding='utf-8') as message_file: 
```
Probably does work, yes. But I suggest you trying it yourself and issuing a pull request if it works 👍

**Comment by adrianosmarinho** [comment]
Alright, I will work on that on my spare time this week :)

**Comment by hugofragata** [comment]
fixed it
