### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by its-mage** [hugofragata/emojify-commits#6]
Installed this, as per the instructions but getting type error

Shell : Zsh,

also tried with bash does not work

**Comment by its-mage** [comment]
full logs:
```python
Traceback (most recent call last):
  File "/home/path_to_project/.git/hooks/prepare-commit-msg", line 37, in <module>
    append_to_file()
  File "/home/path_to_project/.git/hooks/prepare-commit-msg", line 31, in append_to_file
    lines[0] = emojify(lines[0].encode('utf-8'))
  File "/home/path_to_project/.git/hooks/prepare-commit-msg", line 11, in emojify
    p = c.split(' ')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by hugofragata** [comment]
It was prepared to work with Python 2. You are using Python 3 I think, which gives me the same error.

Try it now, it should be fixed. Let me know if it works.

**Comment by its-mage** [comment]
Sure thing, sorry I was not notified by github

**Comment by hugofragata** [comment]
No worries 👍 Just let me know if it's working for you

**Comment by its-mage** [comment]
Yup it worked, so closing the issue.

Thanks for the support and help :+1:
